# Generated by Django 3.0.2 on 2020-06-11 18:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dates', to='unemployapp.Week')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('contact_method', models.CharField(max_length=200)),
                ('work_type', models.CharField(max_length=200)),
                ('results', models.CharField(max_length=200)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='unemployapp.Date')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='unemployapp.Date')),
            ],
        ),
    ]
